services:
  db:
    image: mysql:8.0
    container_name: laravel-mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$(cat /run/secrets/db_root_password)"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: minishop
    secrets:
      - db_root_password
    networks:
      - local
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - .:/var/www
    env_file:
      - .env
    networks:
      - local
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    volumes:
      - .:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    networks:
      - local
    depends_on:
      - app
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=secret
    ports:
      - "8080:80"
    networks:
      - local
    depends_on:
      - db
    restart: unless-stopped

secrets:
  db_root_password:
    file: ./secrets/db_root_password

networks:
  local:
    driver: bridge

volumes:
  mysql_data:
